export const tableofcontent = [
    { tytul: 'Wprowadzenie', strona: 2 },
    { tytul: 'Opis gry', strona: 3 },
    { tytul: 'Elementy', strona: 4 },
    { tytul: 'Przygotowanie gry', strona: 6 },
    { tytul: 'Podstawy gry', strona: 9 },
    { tytul: 'Faza I – Ruch i akcje', strona: 12 },
    { tytul: 'Kościany poker', strona: 14 },
    { tytul: 'Faza II – Walka / Medytacja', strona: 15 },
    { tytul: 'Faza III – Karty', strona: 18 },
    { tytul: 'Walka', strona: 20 },
    { tytul: 'Tura wiedźminina', strona: 22 },
    { tytul: 'Tura potwora', strona: 25 },
    { tytul: 'Wynik walki: potwór', strona: 26 },
    { tytul: 'Wynik walki: wiedźmin', strona: 27 },
    { tytul: 'Trofea i zmęczenie', strona: 29 },
    { tytul: '2 graczy: tura', strona: 30 },
    { tytul: '2 graczy: walka', strona: 31 },
    { tytul: '2 graczy: karty', strona: 32 },
    { tytul: 'Wariant solo', strona: 33 },
    { tytul: 'Glosariusz', strona: 34 },
    { tytul: 'Akcje obszarów', strona: 35 },
]
